version: '3'
services:
  plc:
    image: plc:0.1
    build: ./plc_docker
    # ports:
    #   - 8083:8080
    networks:
      lan:
        ipv4_address: 192.168.95.2
  
  hmi:
    image: hmi:0.1
    build: ./hmi_docker
    # ports:
    #   - 8082:9090
    networks:
      lan:
        ipv4_address: 192.168.95.5
  
  simulation:
    image: simulation:0.1
    build: ./simulation_docker
    deploy:
      replicas: 1
    # ports:
    #   - 8081:80
    networks:
      lan:
        ipv4_address: 192.168.95.10
  
  workstation:
    image: workstation:0.1
    build: ./workstation_docker
    # ports:
    #   - 5900:5900
    networks:
      lan:
        ipv4_address: 192.168.95.6

networks:
  lan:
    ipam:
      driver: default
      config:
        - subnet: "192.168.95.0/24"